# Generated by Django 4.2.10 on 2026-03-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.IntegerField(help_text='GitHub repository ID', unique=True)),
                ('repo_name', models.CharField(help_text='Repository name', max_length=255)),
                ('repo_url', models.URLField(help_text='Full GitHub repository URL')),
                ('repo_description', models.TextField(blank=True, help_text='Original GitHub repository description', null=True)),
                ('is_visible', models.BooleanField(default=False, help_text='Display this project in the public portfolio')),
                ('category', models.CharField(choices=[('MAJOR', 'Major Project'), ('OTHER', 'Other / Lab')], default='OTHER', help_text='Project type: MAJOR shows full details, OTHER shows compact view', max_length=10)),
                ('ai_title', models.CharField(blank=True, help_text='AI-generated project title', max_length=255)),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated project summary (paragraphs for MAJOR, 1-liner for OTHER)')),
                ('key_features', models.JSONField(blank=True, default=list, help_text='List of key features generated by AI')),
                ('tech_stack', models.JSONField(blank=True, default=list, help_text='List of technologies used (extracted by AI)')),
                ('last_synced', models.DateTimeField(auto_now=True, help_text='Last time this project was synced with GitHub')),
                ('ai_generated_at', models.DateTimeField(blank=True, help_text='Timestamp when AI content was generated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this project record was created')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-last_synced'],
                'indexes': [models.Index(fields=['is_visible', '-last_synced'], name='projects_pr_is_visi_0fb6a7_idx'), models.Index(fields=['category', 'is_visible'], name='projects_pr_categor_4ef863_idx')],
            },
        ),
    ]
