# Generated by Django 4.2.10 on 2026-03-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Certificate name to display on portfolio (e.g., 'AWS Certified Solutions Architect')", max_length=255)),
                ('issuer', models.CharField(help_text="Organization that issued the certificate (e.g., 'Amazon Web Services')", max_length=255)),
                ('issued_date', models.DateField(help_text='Date when the certificate was issued')),
                ('pdf_file', models.FileField(help_text='PDF file of the certificate', upload_to='certificates/pdfs/')),
                ('is_visible', models.BooleanField(default=True, help_text='Display this certificate on the portfolio')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this certificate record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time this certificate was updated')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issued_date'],
                'indexes': [models.Index(fields=['is_visible', '-issued_date'], name='projects_ce_is_visi_416439_idx')],
            },
        ),
    ]
