# Generated by Django 6.0.3 on 2026-04-02 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_new_features'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='projects_co_project_3b8aa5_idx',
            old_name='projects_co_project_dd23c6_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='projects_co_created_2ca68a_idx',
            old_name='projects_co_created_ab12fg_idx',
        ),
        migrations.RenameIndex(
            model_name='contactmessage',
            new_name='projects_co_status_5c835e_idx',
            old_name='projects_cm_status__12ab34_idx',
        ),
    ]
