from django.contrib import admin
from django.shortcuts import get_object_or_404
from django.utils.html import format_html
from .models import (
    Project, Certificate, Comment, ContactMessage, 
    WorkExperience, Education, AboutProfile, Skill
)


@admin.register(Certificate)
class CertificateAdmin(admin.ModelAdmin):
    list_display = (
        'name',
        'issuer',
        'issued_date',
        'is_visible_badge',
        'pdf_preview',
        'created_at',
    )
    list_filter = ('is_visible', 'issued_date', 'issuer')
    search_fields = ('name', 'issuer')
    readonly_fields = (
        'created_at',
        'updated_at',
        'pdf_preview_link',
    )
    fieldsets = (
        ('Certificate Info', {
            'fields': ('name', 'issuer', 'issued_date'),
            'description': 'Information about the certificate'
        }),
        ('PDF Upload', {
            'fields': ('pdf_file', 'pdf_preview_link'),
            'description': 'Upload the certificate PDF and preview it'
        }),
        ('Portfolio Control', {
            'fields': ('is_visible',),
            'description': 'Control visibility on the public portfolio'
        }),
        ('Metadata', {
            'fields': ('created_at', 'updated_at'),
            'classes': ('collapse',)
        }),
    )
    
    def is_visible_badge(self, obj):
        """Display a colored badge for visibility status"""
        if obj.is_visible:
            return format_html(
                '<span style="background-color: #00ff88; color: #0a0a0a; padding: 3px 8px; border-radius: 3px; font-weight: bold;">✓ Visible</span>'
            )
        return format_html(
            '<span style="background-color: #ff4444; color: #fff; padding: 3px 8px; border-radius: 3px;">✕ Hidden</span>'
        )
    is_visible_badge.short_description = 'Visibility'
    
    def pdf_preview(self, obj):
        """Show if PDF is uploaded"""
        if obj.pdf_file:
            return format_html(
                '<span style="background-color: #0066ff; color: #fff; padding: 3px 8px; border-radius: 3px;">📄 PDF</span>'
            )
        return format_html(
            '<span style="background-color: #666; color: #fff; padding: 3px 8px; border-radius: 3px;">—</span>'
        )
    pdf_preview.short_description = 'File'
    
    def pdf_preview_link(self, obj):
        """Display a preview/download link for the PDF"""
        if obj.pdf_file:
            return format_html(
                '<a href="{}" target="_blank" style="color: #00ff88; text-decoration: underline;">🔗 View Certificate PDF</a>',
                obj.pdf_file.url
            )
        return "No PDF uploaded"
    pdf_preview_link.short_description = "PDF Link"


@admin.register(Project)
class ProjectAdmin(admin.ModelAdmin):
    list_display = (
        'repo_name',
        'category',
        'is_visible',
        'has_ai_content_badge',
        'last_synced',
    )
    list_filter = ('category', 'is_visible', 'created_at')
    search_fields = ('repo_name', 'ai_title')
    readonly_fields = (
        'github_id',
        'repo_url',
        'repo_description',
        'last_synced',
        'created_at',
        'ai_generated_at',
        'formatted_tech_stack',
        'formatted_features',
    )
    fieldsets = (
        ('GitHub Info', {
            'fields': ('github_id', 'repo_name', 'repo_url', 'repo_description')
        }),
        ('Portfolio Control', {
            'fields': ('is_visible', 'category'),
            'description': 'Control visibility and categorization of this project'
        }),
        ('AI-Generated Content', {
            'fields': (
                'ai_title',
                'ai_summary',
                'formatted_features',
                'formatted_tech_stack',
                'ai_generated_at',
            ),
            'description': 'Content generated by Gemini AI from the GitHub README'
        }),
        ('Metadata', {
            'fields': ('created_at', 'last_synced'),
            'classes': ('collapse',)
        }),
    )
    actions = ['generate_ai_content']
    
    def has_ai_content_badge(self, obj):
        """Display a colored badge for AI content status"""
        if obj.has_ai_content():
            return format_html(
                '<span style="background-color: #00ff88; color: #0a0a0a; padding: 3px 8px; border-radius: 3px; font-weight: bold;">✓ Generated</span>'
            )
        return format_html(
            '<span style="background-color: #666; color: #fff; padding: 3px 8px; border-radius: 3px;">Pending</span>'
        )
    has_ai_content_badge.short_description = 'AI Content'
    
    def formatted_tech_stack(self, obj):
        """Display tech stack as a formatted list"""
        if not obj.tech_stack:
            return "No tech stack generated yet"
        return ', '.join(obj.tech_stack)
    formatted_tech_stack.short_description = "Tech Stack"
    
    def formatted_features(self, obj):
        """Display features as a formatted list"""
        if not obj.key_features:
            return "No features generated yet"
        return '\n'.join([f"• {f}" for f in obj.key_features])
    formatted_features.short_description = "Key Features"
    
    def generate_ai_content(self, request, queryset):
        """Admin action to generate AI content for selected projects"""
        from ai_service.gemini_handler import GeminiProjectAnalyzer
        
        analyzer = GeminiProjectAnalyzer()
        success_count = 0
        error_count = 0
        
        for project in queryset:
            try:
                analyzer.analyze_and_update_project(project)
                success_count += 1
            except Exception as e:
                error_count += 1
                self.message_user(
                    request,
                    f"Error generating content for {project.repo_name}: {str(e)}",
                    level='error'
                )
        
        self.message_user(
            request,
            f"Generated AI content for {success_count} project(s). {error_count} error(s)."
        )
    
    generate_ai_content.short_description = "Generate/Refresh AI content for selected projects"


@admin.register(Comment)
class CommentAdmin(admin.ModelAdmin):
    list_display = (
        'author_name',
        'project',
        'status_badge',
        'created_at',
    )
    list_filter = ('status', 'project', 'created_at')
    search_fields = ('author_name', 'author_email', 'content')
    readonly_fields = (
        'created_at',
        'approved_at',
    )
    fieldsets = (
        ('Comment Info', {
            'fields': ('project', 'author_name', 'author_email', 'content'),
        }),
        ('Moderation', {
            'fields': ('status', 'approved_at'),
        }),
        ('Metadata', {
            'fields': ('created_at',),
            'classes': ('collapse',)
        }),
    )
    actions = ['approve_comments', 'reject_comments']
    
    def status_badge(self, obj):
        """Display colored status badge"""
        colors = {
            'PENDING': '#ff9800',
            'APPROVED': '#00ff88',
            'REJECTED': '#ff4444',
        }
        color = colors.get(obj.status, '#666')
        return format_html(
            '<span style="background-color: {}; color: #fff; padding: 3px 8px; border-radius: 3px; font-weight: bold;">{}</span>',
            color, obj.get_status_display()
        )
    status_badge.short_description = 'Status'
    
    def approve_comments(self, request, queryset):
        """Admin action to approve selected comments"""
        from django.utils import timezone
        updates = queryset.update(status='APPROVED', approved_at=timezone.now())
        self.message_user(request, f"Approved {updates} comment(s).")
    approve_comments.short_description = "Approve selected comments"
    
    def reject_comments(self, request, queryset):
        """Admin action to reject selected comments"""
        updates = queryset.update(status='REJECTED')
        self.message_user(request, f"Rejected {updates} comment(s).")
    reject_comments.short_description = "Reject selected comments"


@admin.register(ContactMessage)
class ContactMessageAdmin(admin.ModelAdmin):
    list_display = (
        'name',
        'subject',
        'status_badge',
        'created_at',
    )
    list_filter = ('status', 'created_at')
    search_fields = ('name', 'email', 'subject', 'message')
    readonly_fields = (
        'created_at',
        'read_at',
    )
    fieldsets = (
        ('Contact Info', {
            'fields': ('name', 'email', 'subject', 'message'),
        }),
        ('Status', {
            'fields': ('status', 'read_at'),
        }),
        ('Metadata', {
            'fields': ('created_at',),
            'classes': ('collapse',)
        }),
    )
    actions = ['mark_as_read', 'mark_as_replied', 'archive_messages']
    
    def status_badge(self, obj):
        """Display colored status badge"""
        colors = {
            'NEW': '#2196f3',
            'READ': '#00ff88',
            'REPLIED': '#4caf50',
            'ARCHIVED': '#666',
        }
        color = colors.get(obj.status, '#666')
        return format_html(
            '<span style="background-color: {}; color: #fff; padding: 3px 8px; border-radius: 3px; font-weight: bold;">{}</span>',
            color, obj.get_status_display()
        )
    status_badge.short_description = 'Status'
    
    def mark_as_read(self, request, queryset):
        """Admin action to mark messages as read"""
        from django.utils import timezone
        updates = queryset.update(status='READ', read_at=timezone.now())
        self.message_user(request, f"Marked {updates} message(s) as read.")
    mark_as_read.short_description = "Mark as read"
    
    def mark_as_replied(self, request, queryset):
        """Admin action to mark messages as replied"""
        updates = queryset.update(status='REPLIED')
        self.message_user(request, f"Marked {updates} message(s) as replied.")
    mark_as_replied.short_description = "Mark as replied"
    
    def archive_messages(self, request, queryset):
        """Admin action to archive messages"""
        updates = queryset.update(status='ARCHIVED')
        self.message_user(request, f"Archived {updates} message(s).")
    archive_messages.short_description = "Archive messages"


@admin.register(WorkExperience)
class WorkExperienceAdmin(admin.ModelAdmin):
    list_display = (
        'job_title',
        'company',
        'current_badge',
        'start_date',
        'order',
    )
    list_filter = ('is_current', 'start_date')
    search_fields = ('job_title', 'company', 'description')
    readonly_fields = ()
    fieldsets = (
        ('Work Info', {
            'fields': ('job_title', 'company', 'description'),
        }),
        ('Dates', {
            'fields': ('start_date', 'end_date', 'is_current'),
        }),
        ('Display', {
            'fields': ('order',),
        }),
    )
    
    def current_badge(self, obj):
        """Display current position badge"""
        if obj.is_current:
            return format_html(
                '<span style="background-color: #00ff88; color: #0a0a0a; padding: 3px 8px; border-radius: 3px; font-weight: bold;">Current</span>'
            )
        return '—'
    current_badge.short_description = 'Status'


@admin.register(Education)
class EducationAdmin(admin.ModelAdmin):
    list_display = (
        'degree',
        'institution',
        'start_date',
        'gpa',
        'order',
    )
    list_filter = ('start_date', 'institution')
    search_fields = ('degree', 'institution', 'description')
    readonly_fields = ()
    fieldsets = (
        ('Education Info', {
            'fields': ('degree', 'institution', 'description', 'gpa'),
        }),
        ('Dates', {
            'fields': ('start_date', 'end_date'),
        }),
        ('Display', {
            'fields': ('order',),
        }),
    )


@admin.register(AboutProfile)
class AboutProfileAdmin(admin.ModelAdmin):
    list_display = ('__str__',)
    readonly_fields = ('updated_at',)
    fieldsets = (
        ('Professional Summary', {
            'fields': ('professional_summary',),
        }),
        ('Resume/CV', {
            'fields': ('resume_file',),
        }),
        ('Social Links', {
            'fields': ('github_url', 'linkedin_url', 'twitter_url', 'other_url'),
        }),
        ('Metadata', {
            'fields': ('updated_at',),
            'classes': ('collapse',)
        }),
    )
    
    def has_add_permission(self, request):
        """Only allow one record"""
        return not AboutProfile.objects.exists()
    
    def has_delete_permission(self, request, obj=None):
        """Prevent deletion"""
        return False


@admin.register(Skill)
class SkillAdmin(admin.ModelAdmin):
    list_display = (
        'name',
        'category',
        'proficiency_bar',
        'featured_badge',
        'order',
    )
    list_filter = ('category', 'is_featured', 'auto_generated')
    search_fields = ('name',)
    readonly_fields = ()
    fieldsets = (
        ('Skill Info', {
            'fields': ('name', 'category'),
        }),
        ('Details', {
            'fields': ('proficiency', 'auto_generated'),
        }),
        ('Display', {
            'fields': ('is_featured', 'order'),
        }),
    )
    
    def proficiency_bar(self, obj):
        """Display proficiency as a progress bar"""
        return format_html(
            '<div style="width: 100px; height: 20px; background-color: #333; border-radius: 3px; overflow: hidden;">'
            '<div style="width: {}%; height: 100%; background-color: #00ff88; transition: width 0.3s;"></div>'
            '</div> {}%',
            obj.proficiency, obj.proficiency
        )
    proficiency_bar.short_description = 'Proficiency'
    
    def featured_badge(self, obj):
        """Display featured badge"""
        if obj.is_featured:
            return format_html(
                '<span style="background-color: #ff9800; color: #fff; padding: 3px 8px; border-radius: 3px; font-weight: bold;">⭐ Featured</span>'
            )
        return '—'
    featured_badge.short_description = 'Featured'
