from django.db import models
from django.utils import timezone


class Certificate(models.Model):
    """
    Represents a certificate earned by the portfolio owner.
    Can be uploaded as PDF and managed through the admin panel.
    """
    
    name = models.CharField(
        max_length=255,
        help_text="Certificate name to display on portfolio (e.g., 'AWS Certified Solutions Architect')"
    )
    issuer = models.CharField(
        max_length=255,
        help_text="Organization that issued the certificate (e.g., 'Amazon Web Services')"
    )
    issued_date = models.DateField(
        help_text="Date when the certificate was issued"
    )
    pdf_file = models.FileField(
        upload_to='certificates/pdfs/',
        help_text="PDF file of the certificate"
    )
    is_visible = models.BooleanField(
        default=True,
        help_text="Display this certificate on the portfolio"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="When this certificate record was created"
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        help_text="Last time this certificate was updated"
    )
    
    class Meta:
        ordering = ['-issued_date']
        verbose_name = "Certificate"
        verbose_name_plural = "Certificates"
        indexes = [
            models.Index(fields=['is_visible', '-issued_date']),
        ]
    
    def __str__(self):
        return f"{self.name} - {self.issuer} ({self.issued_date.year})"


class Project(models.Model):
    """
    Represents a GitHub repository that is displayed in the portfolio.
    Synced from GitHub API and enhanced with AI-generated content.
    """
    
    CATEGORY_CHOICES = [
        ('MAJOR', 'Major Project'),
        ('OTHER', 'Other / Lab'),
    ]
    
    # GitHub Mapping
    github_id = models.IntegerField(unique=True, help_text="GitHub repository ID")
    repo_name = models.CharField(max_length=255, help_text="Repository name")
    repo_url = models.URLField(help_text="Full GitHub repository URL")
    repo_description = models.TextField(blank=True, null=True, help_text="Original GitHub repository description")
    
    # Admin Controls
    is_visible = models.BooleanField(
        default=False,
        help_text="Display this project in the public portfolio"
    )
    category = models.CharField(
        max_length=10,
        choices=CATEGORY_CHOICES,
        default='OTHER',
        help_text="Project type: MAJOR shows full details, OTHER shows compact view"
    )
    
    # AI-Generated Content
    ai_title = models.CharField(
        max_length=255,
        blank=True,
        help_text="AI-generated project title"
    )
    ai_summary = models.TextField(
        blank=True,
        help_text="AI-generated project summary (paragraphs for MAJOR, 1-liner for OTHER)"
    )
    key_features = models.JSONField(
        default=list,
        blank=True,
        help_text="List of key features generated by AI"
    )
    tech_stack = models.JSONField(
        default=list,
        blank=True,
        help_text="List of technologies used (extracted by AI)"
    )
    
    # Metadata
    last_synced = models.DateTimeField(
        auto_now=True,
        help_text="Last time this project was synced with GitHub"
    )
    ai_generated_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="Timestamp when AI content was generated"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="When this project record was created"
    )
    
    class Meta:
        ordering = ['-last_synced']
        verbose_name = "Project"
        verbose_name_plural = "Projects"
        indexes = [
            models.Index(fields=['is_visible', '-last_synced']),
            models.Index(fields=['category', 'is_visible']),
        ]
    
    def __str__(self):
        return f"{self.repo_name} ({self.get_category_display()})"
    
    def has_ai_content(self):
        """Check if AI content has been generated"""
        return bool(self.ai_title and self.ai_summary)
    
    def mark_ai_generated(self):
        """Update the timestamp when AI content is generated"""
        self.ai_generated_at = timezone.now()


class Comment(models.Model):
    """
    Represents a comment on a project made by a visitor.
    Requires admin moderation before being visible.
    """
    
    STATUS_CHOICES = [
        ('PENDING', 'Pending Approval'),
        ('APPROVED', 'Approved'),
        ('REJECTED', 'Rejected'),
    ]
    
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
        related_name='comments',
        help_text="The project this comment is for"
    )
    author_name = models.CharField(
        max_length=255,
        help_text="Name of the person commenting"
    )
    author_email = models.EmailField(
        help_text="Email of the person commenting"
    )
    content = models.TextField(
        help_text="Comment content"
    )
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='PENDING',
        help_text="Approval status of the comment"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="When the comment was created"
    )
    approved_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When the comment was approved"
    )
    
    class Meta:
        ordering = ['-created_at']
        verbose_name = "Comment"
        verbose_name_plural = "Comments"
        indexes = [
            models.Index(fields=['project', 'status']),
            models.Index(fields=['-created_at']),
        ]
    
    def __str__(self):
        return f"Comment by {self.author_name} on {self.project.repo_name}"


class ContactMessage(models.Model):
    """
    Represents a contact form submission from a visitor.
    Admin can view and respond to messages.
    """
    
    STATUS_CHOICES = [
        ('NEW', 'New'),
        ('READ', 'Read'),
        ('REPLIED', 'Replied'),
        ('ARCHIVED', 'Archived'),
    ]
    
    name = models.CharField(
        max_length=255,
        help_text="Visitor's name"
    )
    email = models.EmailField(
        help_text="Visitor's email address"
    )
    subject = models.CharField(
        max_length=255,
        help_text="Message subject"
    )
    message = models.TextField(
        help_text="Message content"
    )
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='NEW',
        help_text="Status of the contact message"
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="When the message was sent"
    )
    read_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When the message was read"
    )
    
    class Meta:
        ordering = ['-created_at']
        verbose_name = "Contact Message"
        verbose_name_plural = "Contact Messages"
        indexes = [
            models.Index(fields=['status', '-created_at']),
        ]
    
    def __str__(self):
        return f"Contact from {self.name} - {self.subject}"


class WorkExperience(models.Model):
    """
    Represents a work experience entry for the About section.
    """
    
    job_title = models.CharField(
        max_length=255,
        help_text="Job title/position"
    )
    company = models.CharField(
        max_length=255,
        help_text="Company name"
    )
    start_date = models.DateField(
        help_text="Start date of employment"
    )
    end_date = models.DateField(
        null=True,
        blank=True,
        help_text="End date of employment (leave blank if current)"
    )
    description = models.TextField(
        help_text="Description of responsibilities and achievements"
    )
    is_current = models.BooleanField(
        default=False,
        help_text="Mark as current position"
    )
    order = models.PositiveIntegerField(
        default=0,
        help_text="Display order (lower numbers appear first)"
    )
    
    class Meta:
        ordering = ['-start_date', 'order']
        verbose_name = "Work Experience"
        verbose_name_plural = "Work Experiences"
    
    def __str__(self):
        return f"{self.job_title} at {self.company}"


class Education(models.Model):
    """
    Represents an education entry for the About section.
    """
    
    degree = models.CharField(
        max_length=255,
        help_text="Degree or qualification (e.g., 'B.Tech Computer Science')"
    )
    institution = models.CharField(
        max_length=255,
        help_text="School/College/University name"
    )
    start_date = models.DateField(
        help_text="Start date of studies"
    )
    end_date = models.DateField(
        null=True,
        blank=True,
        help_text="End date of studies"
    )
    gpa = models.CharField(
        max_length=10,
        blank=True,
        help_text="GPA or CGPA (e.g., '8.25')"
    )
    description = models.TextField(
        blank=True,
        help_text="Additional details about education"
    )
    order = models.PositiveIntegerField(
        default=0,
        help_text="Display order (lower numbers appear first)"
    )
    
    class Meta:
        ordering = ['-start_date', 'order']
        verbose_name = "Education"
        verbose_name_plural = "Educations"
    
    def __str__(self):
        return f"{self.degree} from {self.institution}"


class AboutProfile(models.Model):
    """
    Singleton model for portfolio owner's about information.
    Only one record should exist in the database.
    """
    
    professional_summary = models.TextField(
        help_text="Your professional summary/bio (appears on About section)"
    )
    resume_file = models.FileField(
        upload_to='resume/',
        help_text="Your resume/CV PDF to download"
    )
    github_url = models.URLField(
        blank=True,
        help_text="GitHub profile URL"
    )
    linkedin_url = models.URLField(
        blank=True,
        help_text="LinkedIn profile URL"
    )
    twitter_url = models.URLField(
        blank=True,
        help_text="Twitter/X profile URL"
    )
    other_url = models.URLField(
        blank=True,
        help_text="Any other social/portfolio URL"
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        help_text="Last updated timestamp"
    )
    
    class Meta:
        verbose_name = "About Profile"
        verbose_name_plural = "About Profile"
    
    def __str__(self):
        return "Portfolio Owner Profile"
    
    def save(self, *args, **kwargs):
        """Ensure only one record exists"""
        if AboutProfile.objects.exists() and not self.pk:
            obj = AboutProfile.objects.first()
            obj.professional_summary = self.professional_summary
            obj.resume_file = self.resume_file
            obj.github_url = self.github_url
            obj.linkedin_url = self.linkedin_url
            obj.twitter_url = self.twitter_url
            obj.other_url = self.other_url
            obj.save()
            return
        super().save(*args, **kwargs)


class Skill(models.Model):
    """
    Represents a technical skill or technology.
    Can be manually added or auto-generated from project tech stacks.
    """
    
    CATEGORY_CHOICES = [
        ('LANGUAGE', 'Programming Language'),
        ('FRAMEWORK', 'Framework / Library'),
        ('TOOL', 'Tool / Platform'),
        ('DATABASE', 'Database / Storage'),
        ('OTHER', 'Other'),
    ]
    
    name = models.CharField(
        max_length=100,
        unique=True,
        help_text="Skill name (e.g., 'Python', 'Django', 'React')"
    )
    category = models.CharField(
        max_length=20,
        choices=CATEGORY_CHOICES,
        default='OTHER',
        help_text="Category of this skill"
    )
    proficiency = models.PositiveIntegerField(
        default=50,
        help_text="Proficiency level (0-100)"
    )
    order = models.PositiveIntegerField(
        default=0,
        help_text="Display order"
    )
    is_featured = models.BooleanField(
        default=False,
        help_text="Show in featured skills section"
    )
    auto_generated = models.BooleanField(
        default=False,
        help_text="Was this auto-generated from projects"
    )
    
    class Meta:
        ordering = ['-is_featured', 'order', 'name']
        verbose_name = "Skill"
        verbose_name_plural = "Skills"
    
    def __str__(self):
        return self.name
